name: Check Baota Update

on:
  schedule:
    - cron: '0 */8 * * *'  # 每8小时执行一次
  workflow_dispatch:

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 首先获取最新的 Release 信息
      - name: Get Latest Release
        id: latest_release
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const release = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              return release.data.tag_name;
            } catch (e) {
              return '';  // 如果没有 release 返回空字符串
            }

      # 获取宝塔最新版本并下载
      - name: Get and Download Baota Version
        id: baota_version
        run: |
          # 创建 downloads 目录（如果不存在）
          mkdir -p downloads
          
          # 获取版本号和下载文件
          VERSION=$(curl -s 接口地址获取版本号)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # 下载文件到 downloads 目录
          curl -o "downloads/baota_${VERSION}.zip" 下载地址
          
          # 记录版本信息到文件
          echo "$VERSION" > downloads/latest_version.txt

      # 提交新下载的文件到仓库
      - name: Commit Downloads
        if: steps.latest_release.outputs.result != steps.baota_version.outputs.version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add downloads/
          git commit -m "Update Baota version to ${{ steps.baota_version.outputs.version }}"
          git push

      # 比较版本并决定是否创建新的 Release
      - name: Compare and Create Release
        if: steps.latest_release.outputs.result != steps.baota_version.outputs.version
        uses: actions/github-script@v6
        with:
          script: |
            const version = '${{ steps.baota_version.outputs.version }}';
            const releaseExists = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            }).then(response => 
              response.data.some(release => release.tag_name === version)
            );
            
            if (!releaseExists) {
              // 创建 release 并上传文件
              const release = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: version,
                name: `Release ${version}`,
                body: 'Automated release for Baota version ' + version,
                draft: false,
                prerelease: false
              });
              
              // 可以选择将下载的文件作为 release 资源上传
              const fs = require('fs');
              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.data.id,
                name: `baota_${version}.zip`,
                data: fs.readFileSync(`downloads/baota_${version}.zip`)
              });
            }

