name: Auto Update Bt-Panel

on:
  schedule:
    - cron: '0 0 * * *'  # 定时每天执行
  workflow_dispatch:  # 手动触发

jobs:
  update_bt_panel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Get latest version
      run: |
        banben=$(curl -s https://www.bt.cn/api/panel/get_version?is_version=1)
        echo "Latest version: $banben"

    - name: Add offline download
      run: |
        path="/Cloud_disk/自动保存宝塔版本"
        url="http://download.bt.cn/install/update/LinuxPanel-$banben.zip"
        tool="aria2"
        delete_policy="delete_on_upload_succeed"

        payload="{\"path\":\"$path\",\"urls\":[\"$url\"],\"tool\":\"$tool\",\"delete_policy\":\"$delete_policy\"}"

        curl -X POST \
          -H "Content-Type: application/json;charset=UTF-8" \
          -H "Authorization: ${{ secrets.API_AUTH_TOKEN }}" \
          -d "$payload" \
          ${{ secrets.API_URL }}
