name: 自动/手动自动每天获取最新版宝塔上传到API

on:
  schedule:
    - cron: '0 0 * * *'  # 定时每天执行
  workflow_dispatch:  # 手动触发

jobs:
  update_bt_panel:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        pip install requests

    - name: 获取最新版的宝塔版本号
      id: get_version
      run: |
        echo "banben=$(curl -s https://www.bt.cn/api/panel/get_version?is_version=1)" >> $GITHUB_ENV

    - name: 上传到API网站
      run: |
        source $GITHUB_ENV
        path="/Cloud_disk/自动保存宝塔版本"
        url="http://download.bt.cn/install/update/LinuxPanel-${banben}.zip"
        tool="aria2"
        delete_policy="delete_on_upload_succeed"

        payload="{\"path\":\"$path\",\"urls\":[\"$url\"],\"tool\":\"$tool\",\"delete_policy\":\"$delete_policy\"}"

        curl -X POST \
          -H "Content-Type: application/json;charset=UTF-8" \
          -H "Authorization: ${{ secrets.API_AUTH_TOKEN }}" \
          -d "$payload" \
          "${{ secrets.API_URL }}"

