name: 上传宝塔最新版本

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *' # 每隔7天触发一次

jobs:
  upload_baota_version:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 显示环境变量
        run: echo "DOWNLOAD_DIR=${DOWNLOAD_DIR}"

      - name: 设置下载目录环境变量
        run: echo "DOWNLOAD_DIR=$HOME/bt_download" >> $GITHUB_ENV

      - name: 运行下载脚本
        run: |
          chmod +x download_baota.sh
          ./download_baota.sh

      - name: 传递日期变量
        run: echo "RELEASE_DATE=$(TZ='Asia/Shanghai' date +'%Y年%m月%d日%H时%M分%S秒')" >> $GITHUB_ENV
    
      - name: 传递日期变量版本
        run: echo "RELEASE_DATE1=$(TZ='Asia/Shanghai' date +'%Y%m%d%H%M')" >> "$GITHUB_ENV"
      - name: 创建 GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY1_GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_DATE1 }}
          release_name: 宝塔版本集合
          draft: false
          prerelease: false
   
      - name: 显示环境变量
        run: echo "DOWNLOAD_DIR=${DOWNLOAD_DIR}, RELEASE_DATE=${RELEASE_DATE}"
        

      - name: 上传文件到 GitHub Release
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.MY1_GITHUB_TOKEN }}
         DOWNLOAD_DIR: ${{ env.DOWNLOAD_DIR }}
         BANBEN: ${{ env.BANBEN }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ${{ env.DOWNLOAD_DIR }}/LinuxPanel-${{ env.BANBEN }}.zip
         asset_name: LinuxPanel-${{ env.BANBEN }}.zip
         asset_content_type: application/zip




     
