name: 上传魔方云环境文件

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *' # 每隔7天触发一次

jobs:
  upload_to_release:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v2

    - name: 设置 Python 环境
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: 运行下载脚本
      run: |
        chmod +x download_mofang.sh
        ./download_mofang.sh
        
    - name: 传递日期变量
      run: echo "RELEASE_DATE=$(TZ='Asia/Shanghai' date +'%Y年%m月%d日%H时%M分%S秒')" >> $GITHUB_ENV
    
    - name: 传递日期变量版本
      run: echo "RELEASE_DATE1=$(TZ='Asia/Shanghai' date +'%Y%m%d%H%M')" >> "$GITHUB_ENV"
        
    - name: 创建 GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY1_GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.RELEASE_DATE1 }}
        release_name: 魔方云环境文件 ${{ env.RELEASE_DATE }}
        draft: false
        prerelease: false

    - name: 上传文件到 GitHub Release
      uses: actions/upload-release-asset@v1
      env:
       GITHUB_TOKEN: ${{ secrets.MY1_GITHUB_TOKEN }}
      with:
       upload_url: ${{ github.event.inputs.upload_url }}
       asset_path: release_${{ env.RELEASE_DATE }}.tar.gz  # 使用相同的文件名
       asset_name: release.tar.gz
       asset_content_type: application/gzip

