name: 上传文件到 GitHub Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # 每隔5分钟触发一次

jobs:
  upload_to_release:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v2

    - name: 设置 Python 环境
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: 运行下载脚本
      run: |
        chmod +x download_and_release.sh
        ./download_and_release.sh

    - name: 创建 GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY1_GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: 上传文件到 GitHub Release
      uses: actions/upload-release-asset@v1
      env:
         GITHUB_TOKEN: ${{ secrets.MY1_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_$current_date.tar.gz
        asset_name: release.tar.gz
        asset_content_type: application/gzip
